export const wordPairs = [
  { civilian: "Kucing", undercover: "Anjing" },
  { civilian: "Pizza", undercover: "Burger" },
  { civilian: "Pantai", undercover: "Kolam Renang" },
  { civilian: "Kopi", undercover: "Teh" },
  { civilian: "Sepeda", undercover: "Motor" },
  { civilian: "Apel", undercover: "Pir" },
  { civilian: "Bioskop", undercover: "Teater" },
  { civilian: "Dokter", undercover: "Perawat" },
  { civilian: "Gunung", undercover: "Bukit" },
  { civilian: "Nasi Goreng", undercover: "Mie Goreng" },
  { civilian: "Sungai", undercover: "Danau" },
  { civilian: "Gitar", undercover: "Ukulele" },
  { civilian: "Buku", undercover: "Majalah" },
  { civilian: "Hujan", undercover: "Salju" },
  { civilian: "Ayam Goreng", undercover: "Bebek Goreng" },
  { civilian: "Lipstik", undercover: "Blush On" },
  { civilian: "Superman", undercover: "Batman" },
  { civilian: "Instagram", undercover: "TikTok" },
  { civilian: "Sepatu", undercover: "Sandal" },
  { civilian: "Matahari", undercover: "Bulan" },
  { civilian: "Es Krim", undercover: "Yogurt" },
  { civilian: "Mobil", undercover: "Bus" },
  { civilian: "Hotel", undercover: "Hostel" },
  { civilian: "Pensil", undercover: "Pulpen" },
  { civilian: "Tenis", undercover: "Badminton" },
  { civilian: "Pisang", undercover: "Mangga" },
  { civilian: "Nasi Padang", undercover: "Warung Tegal" },
  { civilian: "Celana Jeans", undercover: "Celana Chino" },
  { civilian: "Whatsapp", undercover: "Telegram" },
  { civilian: "Tukang Ojek", undercover: "Sopir Taksi" },
  { civilian: "Masjid", undercover: "Gereja" },
  { civilian: "Bendera", undercover: "Spanduk" },
  { civilian: "Polisi", undercover: "Satpam" },
  { civilian: "Pensil Warna", undercover: "Crayon" },
  { civilian: "Aquarium", undercover: "Kolam Ikan" },
  { civilian: "Bantal", undercover: "Guling" },
  { civilian: "Kipas Angin", undercover: "AC" },
  { civilian: "Indomie", undercover: "Pop Mie" },
  { civilian: "Kecap", undercover: "Saos" },
  { civilian: "Warung", undercover: "Minimarket" },
];

export function getRandomWordPair() {
  return wordPairs[Math.floor(Math.random() * wordPairs.length)];
}
